config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :topics do
    member do
      post 'upvote'
      post 'downvote'
    end

  end

  root 'topics#index'

  get 'signup' => 'user#new'
  resources :users

  mount Commontator::Engine => '/commontator'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  belongs_to :users
  acts_as_commontable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :topics
  has_many :votes


end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :topic
  belongs_to :users

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end

  def downvote
    @topic = Topic.find(params[:id])
    @topic.votes.first.destroy
    redirect_to(topics_path)
  end

  def score
    @topic.upvote.size - @topic.downvote.size
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
   link = Link.find(params[:link_id])
   vote = Vote.new(:value => params[:value], :user => current_user)
   link.votes << vote
   if vote.persisted?
     redirect_to :back, :notice => "Vote recorded!"
   else
     redirect_to :back, :notice => "You've already voted"
   end
 end

 def update
   link = Link.find(params[:link_id])
   vote = link.votes.where(:user_id => current_user.id).find(params[:id])
   if vote.update(:value => params[:value])
     redirect_to :back, :notice => "Vote updated!"
   else
     redirect_to :back, :notice => "NOT VALID"
   end
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_helper.rb
module UserHelper


end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Redditclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css"> -->
<link href="css/scaffolds.scss" rel="stylesheet">

</head>

<body>
  <div id="page"
    <header>
      <nav>
        <h1>reddit clone
          <small>by: Emanuel Rhodes III</small>
        </h1>
        <ul>
            <% if current_user %>
        <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
    </ul>
      </nav>
    </header>


      <%= yield %>

    <aside>

    </aside>

    <footer>
      <p class="copyright text-muted">Copyright &copy; Your Website 2015</p>
    </footer>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="js/bootstrap.min.js"></script>

 </div>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>
<h3><%= link_to 'New Topic', new_topic_path %></h3>
<table>
  <thead>
    <tr>
      <th>Like</th>
      <th></th>
      <th>Dislike</th>
      <th></th>
      <th>Link</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
        <td><%= pluralize(topic.votes.count, "Vote") %></td>
        <td><%= button_to '-1', downvote_topic_path(topic), method: :post %></td>
        <td></td>
        <td><%= link_to topic.title, topic %></td>
        <td><%= commontator_thread(topic)%></td>
        <td><%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
      </tr>
    <% end %>



  </tbody>
</table>
<br>

<br>


<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css"> -->

<ul class="pagination">
<li><a href="#">&laquo;</a></li>
<li><a href="#">1</a></li>
<li><a href="#">2</a></li>
<li><a href="#">3</a></li>
<li><a href="#">4</a></li>
<li><a href="#">5</a></li>
<li><a href="#">&raquo;</a></li>

app/views/topics/new.html.erb
<h1><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %></h1> 

<h1>New Topic</h1>



<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= link_to @topic.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @topic.description %>
</p>



    <span class="timestamp">
        Posted <%= time_ago_in_words(@topic.created_at) %> ago.
    </span>



<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/user/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<!-- <p>This will be a signup page for new users.</p> -->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<%= @user.name %>
<%= @user.email %>